services:
  postgres:
    image: postgres:17
    container_name: gundam_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gundam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./server/node
      dockerfile: Dockerfile
    container_name: gundam_api
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gundam_db
    ports:
      - "3000:3000"
    volumes:
      - ./server/node:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: pnpm dev

volumes:
  postgres_data: 
